CREATE DATABASE Member;
use Member;

CREATE TABLE admin(
	id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE member(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    Pnumber VARCHAR(11) NOT NULL,
    ssn VARCHAR(14) NOT NULL,
    insurance_name VARCHAR(100),
    join_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);